[package]
name = "planetary_motion"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1.6"
image = "0.23.14"
kiss3d = "0.27.0"
nalgebra = "0.23.0"
